// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvhsrRiQnECwkL6tAs8KsIx3WmcMind4',
    appId: '1:373195947285:web:250b8b56cfc30a64c07d1c',
    messagingSenderId: '373195947285',
    projectId: 'shoppingbase-e4ae3',
    authDomain: 'shoppingbase-e4ae3.firebaseapp.com',
    storageBucket: 'shoppingbase-e4ae3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsXcB3P2ysbPWkkq9OH4Gb3zbzXimbBDI',
    appId: '1:373195947285:android:1c48573fa93bc35bc07d1c',
    messagingSenderId: '373195947285',
    projectId: 'shoppingbase-e4ae3',
    storageBucket: 'shoppingbase-e4ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLsK0W4t6s-76W-StlS9asnqBSKnXJ_KI',
    appId: '1:373195947285:ios:5a7a7f1e4f743d47c07d1c',
    messagingSenderId: '373195947285',
    projectId: 'shoppingbase-e4ae3',
    storageBucket: 'shoppingbase-e4ae3.appspot.com',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLsK0W4t6s-76W-StlS9asnqBSKnXJ_KI',
    appId: '1:373195947285:ios:88442594c81d8919c07d1c',
    messagingSenderId: '373195947285',
    projectId: 'shoppingbase-e4ae3',
    storageBucket: 'shoppingbase-e4ae3.appspot.com',
    iosBundleId: 'com.example.shoppingapp.RunnerTests',
  );
}
